
server:
  servlet:
    context-path: /beneficiario/api

spring:
  datasource:
    url: jdbc:h2:file:./data/demodb
    username: beneficiario_admin
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  jwt:
    secret: uma-chave-secreta-muito-grande-para-o-meu-projeto-jwt-2026